### ISSUE TITLE
No vsCode intellisense or type information

### ISSUE THREAD

**Issue by papiro** [jackfiszr/deno-faker#3]
I would expect when importing `faker` that I can introspect the available methods. Typing in `faker.` doesn't bring up the methods, and when I fill in a method, there is no documentation and no return type information.

**Comment by jackfiszr** [comment]
Apparently [@faker-js/faker](https://github.com/faker-js/faker) is now the official Faker, and it works in Deno when imported from [skypack](https://www.skypack.dev):

    import faker from "https://cdn.skypack.dev/@faker-js/faker@v5.5.3?dts";

    const randomName = faker.name.findName(); // Rowan Nikolaus
    const randomEmail = faker.internet.email(); // Kassandra.Haley@erich.biz
    const randomCard = faker.helpers.createCard(); // random contact card containing many properties

I very much doubt my version will be maintained.

**Comment by papiro** [comment]
Hmmm, you get intellisense when using that version?

**Comment by jackfiszr** [comment]
The issue was due to the main `Faker` class not being explicitly re-exported in the project main entry file. This is now resolved in version v1.1.3 ([available on JSR](https://jsr.io/@jackfiszr/faker@1.1.3)).
